--고객센터 문의 테이블 생성
CREATE TABLE TBL_QNA (
    USER_ID2 VARCHAR2(20) NULL,
    QNA_CONTENT CLOB NULL,
    QNA_REG_DATE2 DATE NULL
);

--알리야스 값
COMMENT ON COLUMN TBL_QNA.USER_ID2 IS '사용자아이디';
COMMENT ON COLUMN TBL_QNA.QNA_CONTENT IS '문의 내용';
COMMENT ON COLUMN TBL_QNA.QNA_REG_DATE2 IS '등록일';

COMMENT ON COLUMN ADMIN.ADMIN_ID IS '관리자아이디';
COMMENT ON COLUMN ADMIN.ADMIN_PWD IS '관리자비밀번호';

ALTER TABLE ADMIN ADD CONSTRAINT XFK_ID FOREIGN KEY(ADMIN_ID) REFERENCES TBL_USER2(USER_ID2);

COMMIT;
ALTER TABLE TBL_QNA ADD CONSTRAINT XPK_QNA PRIMARY KEY(USER_ID2);

ALTER TABLE TBL_QNA ADD CONSTRAINT XFK_QNA FOREIGN KEY(USER_ID2) REFERENCES TBL_USER2(USER_ID2);

ALTER TABLE TBL_HIBOARD DROP COLUMN HIBBS_INDENT;
COMMIT;

--일정만들기 테이블 생성
CREATE TABLE PLAN_DATE (
    P_NO NUMBER(10) NOT NULL
);

ALTER TABLE PLAN_DATE ADD CONSTRAINT FK_P_NO FOREIGN KEY(P_NO) REFERENCES PLAN_MAKE(P_NO);

--알리야스 값


ALTER TABLE PLAN_MAKE ADD P_START DATE;
ALTER TABLE PLAN_MAKE ADD P_END DATE;

COMMENT ON COLUMN PLAN_MAKE.P_START IS '여행 시작일';
COMMENT ON COLUMN PLAN_MAKE.P_END IS '여행 종료일';

--시퀀스 추가
CREATE SEQUENCE SEQ_P_NO
INCREMENT BY 1 
MAXVALUE 999999999999 
MINVALUE 1 
NOCACHE;
--시퀀스 조회
SELECT * FROM USER_SEQUENCES;

--
ALTER TABLE PLAN_DATE ADD P_DAY NUMBER(8);
COMMENT ON COLUMN PLAN_DATE.P_DAY IS '년월일';
ALTER TABLE PLAN_DATE ADD P_PLACE VARCHAR2(30);
COMMENT ON COLUMN PLAN_DATE.P_PLACE IS '여행 장소';

ALTER TABLE PLAN_MAKE MODIFY P_END NUMBER(8);

ALTER TABLE PLAN_MAKE RENAME COLUMN P_NO TO P_NO_SEQ;
ALTER TABLE PLAN_DATE RENAME COLUMN P_NO TO P_NO_SEQ;

