DELETE 
  FROM TBL_USER
 WHERE USER_ID = 'user0';
 
 commit;
 
UPDATE TBL_USER
   SET
STATUS = 'Y';

ALTER TABLE TBL_USER2 DROP COLUMN USER_AGE2;

INSERT INTO TBL_USER2 (
    USER_ID2,
    USER_PWD2,
    USER_NAME2,
    USER_EMAIL2,
    STATUS2,
    REG_DATE2,
    GENDER2,
    USER_BIRTH2)
    VALUES 
    (#{},
);

SELECT
    USER_ID2,
    NVL(USER_PWD2,'') AS USER_PWD2,
    NVL(USER_NAME2,'') AS USER_NAME2,
    NVL(USER_EMAIL2,'') AS USER_EMAIL2,
    NVL(STATUS2,'') AS STATUS,
    NVL(TO_CHAR(REG_DATE2, 'YYYY.MM.DD HH24:MI:SS'),'') AS REG_DATE2,
    NVL(GENDER2, '') AS GENDER2,
    NVL(USER_BIRTH2,'') AS USER_BIRTH2
FROM
    TBL_USER2
WHERE
    USER_ID2 = #{value}