CREATE SEQUENCE P_NO_SEQ
MINVALUE 1
MAXVALUE 9999999999999999999999999999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER
NOCYCLE ;

DROP SEQUENCE P_NO_SEQ;

commit;



SELECT * FROM USER_SEQUENCES;


SELECT P_NO_SEQ.NEXTVAL FROM DUAL;

--테이블 데이터 삭제--
DELETE FROM PLAN_MAKE WHERE USER_ID2 = 'qwer';

commit;
 
 
ALTER TABLE PLAN_DATE DROP COLUMN P_NO_SEQ;
 
DELETE FROM PLAN_DATE
 WHERE P_NO_SEQ = 0;

DELETE FROM PLAN_DATE
 WHERE P_NO_SEQ = 9;
 
 DELETE FROM PLAN_DATE
 WHERE P_NO_SEQ = 88;
 
 COMMIT;
 
 SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'P_NO_SEQ';
 
 ALTER SEQUENCE P_NO_SEQ INCREMENT BY -1;
 
 SELECT P_NO_SEQ.NEXTVAL FROM DUAL;
 
 ALTER SEQUENCE P_NO_SEQ INCREMENT BY 1;
 
 
 
 ALTER TABLE PLAN_MAKE MODIFY P_TITLE VARCHAR2(50);
 
 
SELECT
    NVL(P_DAY, '') AS P_DAY,
    NVL(P_PLACE,'') AS P_PLACE,
    NVL(USER_ID2,'') AS USER_ID2
FROM
    PLAN_DATE
WHERE USER_ID2 = 'qwer';


SELECT
    NVL(P_DAY, '') AS P_DAY,
    NVL(P_PLACE,'') AS P_PLACE,
    NVL(USER_ID2,'') AS USER_ID2,
    P_NO_SEQ
FROM
    PLAN_DATE
WHERE  P_NO_SEQ = 1;


SELECT
    A.P_NO_SEQ,
    NVL(A.USER_ID2,'') AS USER_ID2,
    NVL(A.P_TITLE,'') AS P_TITLE,
    NVL(TO_CHAR(A.REG_DATE2, 'YYYY.MM.DD'),'') AS REG_DATE2,
    NVL(A.P_START,'') AS P_START,
    NVL(A.P_END,'') AS P_END,
    NVL(B.P_DAY,'') AS P_DAY,
    NVL(B.P_PLACE,'') AS P_PLACE
FROM
    PLAN_MAKE A, PLAN_DATE B
WHERE 
      A.USER_ID2 = 
  AND A.P_NO_SEQ = B.P_NO_SEQ2;
  
INSERT INTO PLAN_DATE (
    P_DAY,
    P_PLACE,
    P_NO_SEQ
) VALUES (
    20210226,
    '시카고',
    1
);

SELECT P_NO_SEQ2.NEXTVAL FROM DUAL;
SELECT
    NVL(A.P_DAY, '') AS P_DAY,
    NVL(A.P_PLACE,'') AS P_PLACE,
    A.P_NO_SEQ2
FROM
    PLAN_DATE A, PLAN_MAKE B
    
WHERE P_NO_SEQ = 1
  AND A.P_NO_SEQ2 = B.P_NO_SEQ;
  
  INSERT INTO PLAN_DATE (
    P_DAY,
    P_PLACE,
    P_NO_SEQ2
) VALUES ( 
    20210215,
    'jeju',
    1
);

SELECT P_NO_SEQ2.NEXTVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES;

SELECT
    ADMIN_ID, 
    NVL(ADMIN_PWD, '') AS ADMIN_PWD
FROM ADMIN
WHERE 
    ADMIN_ID = 'qwer';


SELECT 
    
    B.USER_ID2, 
    NVL(B.USER_PWD2, '') AS USER_PWD2, 
    NVL(B.USER_NAME2, '') AS USER_NAME2, 
    NVL(B.USER_EMAIL2, '') AS USER_EMAIL2, 
    NVL(B.STATUS2, 'N') AS STATUS2, 
    NVL(TO_CHAR(B.REG_DATE2, 'YYYY.MM.DD'), '') AS REG_DATE2,
    NVL(B.GENDER2, '') AS GENDER2,
    NVL(B.USER_BIRTH2, '') AS USER_BIRTH2
FROM 
    ADMIN A, TBL_USER2 B;

ALTER TABLE ADMIN DROP CONSTRAINT ADMIN_ID;

--2/26--
ALTER TABLE TBL_USER2 ADD ADMIN2 VARCHAR(30);
COMMIT;
COMMENT ON COLUMN TBL_USER2.ADMIN2 IS '관리자(true,false)';

CREATE ROLE ADMIN2;
GRANT CREATE SESSION, CREATE TABLE TO ADMIN2;
GRANT ADMIN2 TO USER_ID2;

DELETE FROM TBL_USER2
 WHERE USER_ID2 = 'gpfud0760124';
 
 