
  CREATE TABLE TBL_USER
   (	
   USER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	USER_PWD VARCHAR2(20 BYTE), 
	USER_NAME VARCHAR2(30 BYTE), 
	USER_EMAIL VARCHAR2(50 BYTE), 
	STATUS CHAR(1 BYTE), 
	GENDER CHAR(1 BYTE), 
	USER_AGE NUMBER(6,0), 
	REG_DATE DATE, 
	USER_BIRTH CHAR(8 BYTE), 
	 CONSTRAINT XPK_USER PRIMARY KEY (USER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "TBL_USER"."USER_ID" IS '사용자 아이디';
   COMMENT ON COLUMN "TBL_USER"."USER_PWD" IS '비밀번호';
   COMMENT ON COLUMN "TBL_USER"."USER_NAME" IS '사용자 명';
   COMMENT ON COLUMN "TBL_USER"."USER_EMAIL" IS '사용자 이메일';
   COMMENT ON COLUMN "TBL_USER"."STATUS" IS '사용여부(Y: 사용, N: 정지)';
   COMMENT ON COLUMN "TBL_USER"."GENDER" IS '성별(M:남자, F:여자)';
   COMMENT ON COLUMN "TBL_USER"."USER_AGE" IS '나이';
   COMMENT ON COLUMN "TBL_USER"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TBL_USER"."USER_BIRTH" IS '생년월일';


--tbl_user2

  CREATE TABLE TBL_USER2
   (	
   USER_ID2 VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    USER_PWD2 VARCHAR2(20 BYTE), 
	USER_NAME2 VARCHAR2(30 BYTE), 
	USER_EMAIL2 VARCHAR2(50 BYTE), 
	STATUS2 CHAR(1 BYTE), 
	REG_DATE2 DATE, 
	GENDER2 CHAR(1 BYTE), 
	USER_BIRTH2 CHAR(8 BYTE), 
	 CONSTRAINT XPK_USER2 PRIMARY KEY (USER_ID2)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "TBL_USER2"."USER_ID2" IS '사용자 아이디';
   COMMENT ON COLUMN "TBL_USER2"."USER_PWD2" IS '비밀번호';
   COMMENT ON COLUMN "TBL_USER2"."USER_NAME2" IS '사용자 명';
   COMMENT ON COLUMN "TBL_USER2"."USER_EMAIL2" IS '사용자 이메일';
   COMMENT ON COLUMN "TBL_USER2"."STATUS2" IS '사용여부(Y:사용, N:정지)';
   COMMENT ON COLUMN "TBL_USER2"."REG_DATE2" IS '등록일';
   COMMENT ON COLUMN "TBL_USER2"."GENDER2" IS '성별(W:여자, M:남자)';
   COMMENT ON COLUMN "TBL_USER2"."USER_BIRTH2" IS '생년월일';

--qna_hiboard

  CREATE TABLE QNA_HIBOARD
   (
   QNA_HIBBS_SEQ NUMBER(12,0) NOT NULL ENABLE, 
	USER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	QNA_HIBBS_GROUP NUMBER(12,0), 
	QNA_HIBBS_ORDER NUMBER(10,0), 
    QNA_HIBBS_INDENT NUMBER(10,0), 
	QNA_HIBBS_TITLE VARCHAR2(150 BYTE), 
	QNA_HIBBS_CONTENT CLOB, 
	QNA_HIBBS_READ_CNT NUMBER(10,0), 
	REG_DATE DATE, 
	QNA_HIBBS_PARENT NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT XPK_QNA_HIBOARD PRIMARY KEY (QNA_HIBBS_SEQ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM 
 LOB (QNA_HIBBS_CONTENT) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_SEQ" IS '게시물 번호(시퀀스:SEQ_HIBOARD_SEQ)';
   COMMENT ON COLUMN "QNA_HIBOARD"."USER_ID" IS '사용자 아이디';
   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_GROUP" IS '그룹번호';
   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_ORDER" IS '그룹 내 순서';
   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_TITLE" IS '게시물 제목';
   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_CONTENT" IS '게시물 내용';
   COMMENT ON COLUMN "QNA_HIBOARD"."QNA_HIBBS_READ_CNT" IS '게시물 조회수';
   COMMENT ON COLUMN "QNA_HIBOARD"."REG_DATE" IS '게시물 등록일';


--qna_hiboard_file

  CREATE TABLE QNA_HIBOARD_FILE
   (QNA_HIBBS_SEQ NUMBER(12,0) NOT NULL ENABLE, 
	QNA_FILE_SEQ NUMBER(3,0) NOT NULL ENABLE, 
	QNA_FILE_ORG_NAME VARCHAR2(100 BYTE), 
	QNA_FILE_NAME VARCHAR2(50 BYTE), 
	QNA_FILE_EXT VARCHAR2(20 BYTE), 
	QNA_FILE_SIZE NUMBER(12,0), 
	REG_DATE DATE, 
	 CONSTRAINT XPK_QNA_HIBOARD_FILE PRIMARY KEY (QNA_HIBBS_SEQ, QNA_FILE_SEQ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_HIBBS_SEQ" IS '게시물 번호(QNA_HIBOARD:QNA_HIBBS_SEQ)';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_FILE_SEQ" IS '파일번호(HIBBS_SEQ MAX + 1)';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_FILE_ORG_NAME" IS '원본 파일명';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_FILE_NAME" IS '파일명';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_FILE_EXT" IS '파일 확장자';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."QNA_FILE_SIZE" IS '파일 크기';
   COMMENT ON COLUMN "QNA_HIBOARD_FILE"."REG_DATE" IS '등록일';

--plan_make 

  CREATE TABLE PLAN_MAKE
   (P_NO_SEQ NUMBER(12,0), 
	USER_ID2 VARCHAR2(100 BYTE), 
	P_TITLE VARCHAR2(50 BYTE), 
	REG_DATE2 DATE, 
	P_START VARCHAR2(10 BYTE), 
	P_END VARCHAR2(10 BYTE), 
	 PRIMARY KEY (P_NO_SEQ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE, 
	 CONSTRAINT FK_USER_ID2 FOREIGN KEY (USER_ID2)
	  REFERENCES PORTFOLIO.TBL_USER2 (USER_ID2) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "PLAN_MAKE"."P_NO_SEQ" IS '일정번호';
   COMMENT ON COLUMN "PLAN_MAKE"."USER_ID2" IS '아이디';
   COMMENT ON COLUMN "PLAN_MAKE"."P_TITLE" IS '제목';
   COMMENT ON COLUMN "PLAN_MAKE"."REG_DATE2" IS '등록일';
   COMMENT ON COLUMN "PLAN_MAKE"."P_START" IS '여행 시작일';
   COMMENT ON COLUMN "PLAN_MAKE"."P_END" IS '여행 종료일';



--plan_date

  CREATE TABLE PLAN_DATE
   (P_DAY VARCHAR2(8 BYTE), 
	P_PLACE VARCHAR2(100 BYTE), 
	P_NO_SEQ2 NUMBER(12,0), 
    USER_ID2 VARCHAR2(100 BYTE), 
	 CONSTRAINT FK_P_NO_SEQ FOREIGN KEY (P_NO_SEQ2)
	  REFERENCES PORTFOLIO.PLAN_MAKE (P_NO_SEQ) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "PLAN_DATE"."P_DAY" IS '년월일';
   COMMENT ON COLUMN "PLAN_DATE"."P_PLACE" IS '여행 장소';
   COMMENT ON COLUMN "PLAN_DATE"."P_NO_SEQ2" IS '일정번호';

--TBL_HIBOARD

  CREATE TABLE TBL_HIBOARD
   (HIBBS_SEQ NUMBER(12,0) NOT NULL ENABLE, 
	USER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	HIBBS_GROUP NUMBER(12,0), 
	HIBBS_ORDER NUMBER(10,0), 
	HIBBS_INDENT NUMBER(10,0), 
	HIBBS_TITLE VARCHAR2(150 BYTE), 
	HIBBS_CONTENT CLOB, 
	HIBBS_READ_CNT NUMBER(10,0), 
	REG_DATE DATE, 
	HIBBS_PARENT NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE, 
	TRAV_PLAN CLOB, 
	 CONSTRAINT SPK_HIBOARD PRIMARY KEY (HIBBS_SEQ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM
 LOB (HIBBS_CONTENT) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB (TRAV_PLAN) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_SEQ" IS '게시물 번호(시퀀스:SEQ_HIBOARD_SEQ)';
   COMMENT ON COLUMN "TBL_HIBOARD"."USER_ID" IS '사용자 아이디';
   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_GROUP" IS '그룹번호';
   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_ORDER" IS '그룹 내 순서';
   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_TITLE" IS '게시물 제목';
   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_CONTENT" IS '게시물 내용';
   COMMENT ON COLUMN "TBL_HIBOARD"."HIBBS_READ_CNT" IS '게시물 조회수';
   COMMENT ON COLUMN "TBL_HIBOARD"."REG_DATE" IS '게시물 등록일';

--TBL_HIBOARD_FILE

  CREATE TABLE TBL_HIBOARD_FILE
   (HIBBS_SEQ NUMBER(12,0) NOT NULL ENABLE, 
	FILE_SEQ NUMBER(3,0) NOT NULL ENABLE, 
	FILE_ORG_NAME VARCHAR2(100 BYTE), 
	FILE_NAME VARCHAR2(50 BYTE), 
	FILE_EXT VARCHAR2(20 BYTE), 
	FILE_SIZE NUMBER(12,0), 
	REG_DATE DATE, 
	 CONSTRAINT XPK_HIBOARD_FILE PRIMARY KEY (HIBBS_SEQ, FILE_SEQ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;

   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."HIBBS_SEQ" IS '게시물 번호(TBL_HIBOARD:HIBBS_SEQ)';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."FILE_SEQ" IS '파일번호(HIBBS_SEQ MAX + 1)';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."FILE_ORG_NAME" IS '원본 파일명';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."FILE_NAME" IS '파일명';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."FILE_EXT" IS '파일 확장자';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."FILE_SIZE" IS '파일 크기';
   COMMENT ON COLUMN "TBL_HIBOARD_FILE"."REG_DATE" IS '등록일';


--SEQUENCE 처리
CREATE SEQUENCE  "PORTFOLIO"."P_NO_SEQ2"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;

CREATE SEQUENCE  "PORTFOLIO"."P_NO_SEQ"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;

CREATE SEQUENCE  "PORTFOLIO"."SEQ_HIBOARD_SEQ"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;

CREATE SEQUENCE  "PORTFOLIO"."SEQ_QNA_HIBOARD_SEQ"  
MINVALUE 1 
MAXVALUE 999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE;

SELECT * FROM USER_SEQUENCES;

DROP SEQUENCE P_NO_SEQ;
DROP SEQUENCE P_NO_SEQ2;
DROP SEQUENCE SEQ_HIBOARD_SEQ;
DROP SEQUENCE SEQ_QNA_HIBOARD_SEQ;